cart_app/urls.py
from django.urls import path,include
from . import views
app_name='cart_app'
urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('', views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from ecommerce import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
path('ecommerce_app/', include('ecommerceapp.urls')),
path('search_app/', include('search_app.urls')),
path('cart/', include('cart_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


#search_app/
#ecommerce_app/

ecommerceapp/urls.py
from django.urls import path,include
from . import views
app_name='ecommerceapp'
urlpatterns = [
    path('', views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail,name='prodCatDetail'),

]

search_app/urls.py
from django.urls import path,include
from . import views
app_name='search_app'
urlpatterns = [
    path('s/', views.Search_Results,name='Search_Results'),


]

cart_app/models.py
from django.db import models
from ecommerceapp.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table:'Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)


#for storing added cart items
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table:'CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return '{}'.format(self.product)

ecommerceapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.



class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('ecommerceapp:products_by_category',args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'
    def __str__(self):
        return '{}'.format(self.name)
    def get_url(self):
        return reverse('ecommerceapp:prodCatDetail',args=[self.category.slug,self.slug])

search_app/models.py
from django.db import models

# Create your models here.

cart_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerceapp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def _cart_id(request):               #(aadding elements to the cart)
    cart=request.session.session_key   #for already existed session_key
    if not cart:
        cart=request.session.create()  #if not,then creating a new session
    return cart
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
         cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart_app:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart_app:cart_detail')


def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart_app:cart_detail')

ecommerceapp/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,InvalidPage,EmptyPage

# Create your views here.
#def index(request):
    #return HttpResponse('hi hello')


def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        page=Paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})

def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)

    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

search_app/views.py
from ecommerceapp.models import Product
from django.db.models import Q
from django.shortcuts import render

# Create your views here.
def Search_Results(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))

    return render(request,'search.html',{'query':query,'products':products})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100&display=swap" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription%}{% endblock %}">
<title>{% block title%}{% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
 <script src="{% static 'js/popper.min.js' %}"></script>
 <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is a cart page.proceed to review your item and place your order ...
{% endblock %}
{% block title %}
    cart -ABC Company private limited
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shoppin cart is empty...</h1>
        <br>
        <p class="text-center">
           please click<a href="{% url 'ecommerceapp:allProdCart' %}">Here</a>to continue Shopping..
        </p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart.
        </h1>
        <br>

    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        Your Items..

                    </th>
                </tr>

                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="{{cart_item.product.get_absolute_url}}"><img src="{{cart_item.product.image.url}}" alt="image" style="height: 100px; width: 30%;" class="float-left rounded custom_image"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        <br>
                        SKU:{{cart_item.product.id}}
                        <br>
                        <br>
                        PRICE:${{cart_item.product.price}}
                        <br>
                        <br>
                        Qty: <b>{{cart_item.quantity}} * {{cart_item}}</b>
                    </td>
                    <td>
                        $ {{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa fa-plus custom_icon"> </i></a>
                        &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                    {% else %}
                    <td>
                        &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th>
                        Check out
                    </th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            please review your shopping cart items before proceeding with the order payment..
                        </td>
                    </tr>
                <tr>
                    <td class="text-left">
                        Your total is : <strong>{{total}}</strong>

                    </td>
                </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'ecommerceapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_ebutton">Continue Shopping</a>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155}}
    {% else %}
        Welcome to MALABAR STORES where you can buy different items...
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} - MALABAR Stores
    {% else %}
        See our new Collections - MALABAR Stores
    {% endif %}
{% endblock %}

{% block content %}
{% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx_auto">
            <p><a href="{% url 'ecommerceapp:allProdCat' %}">Our Product Collections</a> </p>
            </div>
        </div>
    </div>
{% endif %}
<div class="mx_auto">
    {% if category %}
    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" width="1250px;">

</div>
    <br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
<div>
    {% else %}
    <div>
        <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="our products" width="1250px;">
    </div>
    <br>
    <div>
        <h4 class="text-center "><b>Our products Collections</b></h4>
        <p class="text-justify my_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
    </div>
    {% endif %}
    <div class="container">
        <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}" style="height: 200px; width: 100%; display: block;"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
        </div>
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}"></a>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <br>
    </div>
</div>

{% endblock %}

templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; ABC tech pvt limited.All rights Reserverd</p>
</div>

templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ecommerceapp:allProdCat' %}"><img src="{% static 'img/logo5.png' %}" alt="image" width="300px;" height="200px;">
    </center>
</header>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ecommerceapp:allProdCat' %}">Shop</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'ecommerceapp:allProdCat' %}"></a>All Products</li>
               {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart_app:cart_detail' %}" ><i class="fa fa-shopping-cart">({{item_count}})</i></a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" method="get" action="{% url 'search_app:Search_Results' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        {{ product.description|truncatewords:155}}
{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }} - MALABAR Stores
    {% endif %}
{% endblock %}

{% block content %}

<div>
    <div>
        <a href="{% url 'ecommerceapp:allProdCat' %}">Home</a>
    </div>
</div>
<div>
    <div>
        <a href="{{ product.category.get_url }}">{{product.category}}</a><a>{{product.name}}</a>
    </div>
</div>
<div class="container">
    <br>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div style="min-width:18rem;">
             <img src="{{product.image.url}}" alt="{{product.name}}">
        </div>
    </div>

    <div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1>{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p>{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p><b>Out of Stock</b></p>
            {% else %}
            <a href="{% url 'cart_app:add_cart' product.id %}" class="btn btn-danger">Add To Cart</a>
            {% endif %}
        </div>
        </div>
    </div>
            </div>


</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    we have variety of collections...
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for <b>"{{query}}"</b></p>
</div>
<div class="container">
        <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}" style="height: 200px; width: 100%; display: block;"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
            {% empty %}
            <div class="row mx_auto">
                <p class="text-center my_search_text">0 results found...</p>
            </div>
            {% endfor %}
        </div>
</div>

{% endblock %}